app_task:
    resource: "@AppBundle/Resources/config/routing/task.php"
    prefix:   /task
app_expense:
    resource: "@AppBundle/Resources/config/routing/expense.php"
    prefix:   /expense
app_income:
    resource: "@AppBundle/Resources/config/routing/income.php"
    prefix:   /income

