AppBundle\Entity\Task:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\TaskRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        plannedWork:
            type: decimal
            precision: '5'
            scale: '2'
            column: planned_work
        dueDate:
            type: datetime
            nullable: true
            column: due_date
    lifecycleCallbacks: {  }
    manyToOne:
        user:
          targetEntity: AppBundle\Entity\User
          joinColumn:
            name: user_id
            referencedColumnName: id
